# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-24 07:08
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150)),
                ('body', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('video', models.CharField(default='https://www.youtube.com/embed/kNst9WrrJRA', max_length=300)),
                ('start_day', models.DateField(default=datetime.date.today)),
                ('start_time', models.TimeField(default=datetime.datetime.now)),
                ('arena', models.CharField(blank=True, max_length=80)),
                ('lat', models.FloatField(blank=True, default=20)),
                ('lng', models.FloatField(blank=True, default=20)),
                ('vs', models.ImageField(blank=True, upload_to='imgs')),
                ('score', models.CharField(blank=True, max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('biography', models.TextField(blank=True)),
                ('age', models.IntegerField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='imgs')),
                ('height', models.FloatField(blank=True, default=20)),
                ('weight', models.FloatField(blank=True, default=20)),
                ('birthplace', models.CharField(blank=True, max_length=80)),
                ('previously', models.TextField(blank=True)),
                ('nba_debut', models.IntegerField(blank=True, default=20)),
                ('years_in_nba', models.IntegerField(blank=True, default=20)),
                ('position', models.CharField(max_length=80)),
                ('number', models.IntegerField(blank=True, default=20)),
                ('games_played', models.IntegerField(blank=True, default=20)),
                ('field_goals_made', models.IntegerField(blank=True, default=20)),
                ('points', models.IntegerField(blank=True, default=20)),
                ('field_goal', models.FloatField(blank=True, default=20)),
                ('three_points', models.FloatField(blank=True, default=20)),
                ('free_throw', models.FloatField(blank=True, default=20)),
                ('offensive_rebounds', models.IntegerField(blank=True, default=20)),
                ('deffensive_rebounds', models.IntegerField(blank=True, default=20)),
                ('rebounds', models.IntegerField(blank=True, default=20)),
                ('assists', models.IntegerField(blank=True, default=20)),
                ('steals', models.IntegerField(blank=True, default=20)),
                ('turn_overs', models.IntegerField(blank=True, default=20)),
                ('fouls', models.IntegerField(blank=True, default=20)),
            ],
        ),
        migrations.CreateModel(
            name='Player_Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='player_photos')),
                ('player', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='rockets.Player')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('avatar', models.ImageField(blank=True, upload_to='user_imgs')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('conference', models.CharField(max_length=80)),
                ('division', models.CharField(max_length=80)),
                ('founded', models.IntegerField(blank=True, default=20)),
                ('history', models.TextField(blank=True)),
                ('arena', models.CharField(blank=True, max_length=80)),
                ('location', models.CharField(blank=True, max_length=80)),
                ('team_colors', models.CharField(choices=[('R', 'Red'), ('S', 'Silver'), ('B', 'Black'), ('W', 'White')], max_length=200)),
                ('general_manager', models.CharField(blank=True, max_length=80)),
                ('head_coach', models.CharField(blank=True, max_length=80)),
                ('ownership', models.CharField(blank=True, max_length=80)),
                ('championships', models.IntegerField(blank=True, default=20)),
                ('uniforms', models.ImageField(blank=True, upload_to='imgs')),
                ('match', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='rockets.Match')),
                ('player', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='rockets.Player')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(blank=True, default=20)),
                ('seating_map', models.ImageField(blank=True, upload_to='imgs')),
                ('seat_number', models.IntegerField(blank=True, default=20)),
                ('creditcard', models.CharField(blank=True, max_length=80)),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='player',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='rockets.Player'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
