# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-24 07:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rockets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='assists',
            field=models.FloatField(blank=True, default=20),
        ),
        migrations.AlterField(
            model_name='player',
            name='deffensive_rebounds',
            field=models.FloatField(blank=True, default=20),
        ),
        migrations.AlterField(
            model_name='player',
            name='field_goals_made',
            field=models.FloatField(blank=True, default=20),
        ),
        migrations.AlterField(
            model_name='player',
            name='fouls',
            field=models.FloatField(blank=True, default=20),
        ),
        migrations.AlterField(
            model_name='player',
            name='offensive_rebounds',
            field=models.FloatField(blank=True, default=20),
        ),
        migrations.AlterField(
            model_name='player',
            name='points',
            field=models.FloatField(blank=True, default=20),
        ),
        migrations.AlterField(
            model_name='player',
            name='rebounds',
            field=models.FloatField(blank=True, default=20),
        ),
        migrations.AlterField(
            model_name='player',
            name='steals',
            field=models.FloatField(blank=True, default=20),
        ),
        migrations.AlterField(
            model_name='player',
            name='turn_overs',
            field=models.FloatField(blank=True, default=20),
        ),
    ]
