# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-24 08:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rockets', '0002_auto_20171224_1026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='match',
        ),
        migrations.RemoveField(
            model_name='team',
            name='player',
        ),
    ]
