# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-26 10:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rockets', '0003_auto_20171224_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='match',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='rockets.Match'),
            preserve_default=False,
        ),
    ]
